### ISSUE TITLE
cannot find the maven repo

### ISSUE THREAD

**Issue by shanta5489** [cagataygurturk/aws-lambda-java-boilerplate#2]
Hi, 

Looks like the maven repo is unreachable: http://maven.cagataygurturk.com/releases

Please help find the right location. Is the lib still supported?

Thank you.

**Comment by cubiccompass** [comment]
Confirmed. The repo is no longer hosting. http://maven.cagataygurturk.com/releases

I resorted to git cloning and building this jar locally.

**Comment by cagataygurturk** [comment]
The required dependency (aws-lambda-local-runner) is still being served at http://maven.cagataygurturk.com/releases/com/cagataygurturk/aws-lambda-local-runner/0.0.1/aws-lambda-local-runner-0.0.1.jar
